### ISSUE TITLE
KeyPress Handler for Basic Authentication Form

### ISSUE THREAD

**Issue by StephenCote** [jrogelstad/featherbone#34]
On the current basic authentication form (username, password), specifically the password field, add a keypress handler for {event}.keyCode == 13 to submit form without having to tab to or click on the submit button.

**Comment by jrogelstad** [comment]
Support added: https://github.com/jrogelstad/featherbone/commit/ea8a19fcbdc86f0099d5dfef5b1d162d598e42f3
