### ISSUE TITLE
Plain text credential posted when user created

### ISSUE THREAD

**Issue by StephenCote** [jrogelstad/featherbone#35]
Password issues when creating a user:

1) plain text credential is  being logged/written to console on user create (this is understood as being in development, but something to filter out before getting anywhere close to production)

2) user and credential are posted together over an unencrypted connection. Add HTTPS/TLS support, and investigate/confirm either a) hooks to third party libraries allow you to wholly bypass touching passwords, and/or that they protect the credential at the time of account creation.

**Comment by jrogelstad** [comment]
Not sure what to do with this one.

1. Ok, sure, I can put some code in there that conditionally hides passwords from the console log, but if you have access to the console, then you have access to server code where you could comment out this condition, so have we really secured anything? Kind of seems like if you have access to the server, you have complete access to everything no matter what.

2. I assume HTTPS/TLS is an implementation issue that I don't need to add anything for here, or do I? I don't intend to implement 3rd party authentication in the open source version of this software, but that is a good commercial (again production) option.

So all that said is there something I still can and should do here, or just punt until production?

**Comment by StephenCote** [comment]
Leave a note to take it out at some point or put a regexp in there to scrub
it. This will turn into an issue if and when someone gains access to log
files. You're correct that having access to the server means someone could
do far worse.
