### ISSUE TITLE
Privilege Escalation

### ISSUE THREAD

**Issue by StephenCote** [jrogelstad/featherbone#37]
Reproduction Steps:

1. Authenticate as a non-super user
2. Edit account for context user
3. Set context user as a super user
4. Save

Observed Results:

User

1. is promoted to super user

Expected Results:

1. User is not authorized to edit field
2. User is not authorized to affect change to escalate privilege.

**Comment by jrogelstad** [comment]
Fixed: https://github.com/jrogelstad/featherbone/commit/b504a488e9294536bd886bf5185c2932794dcdea
